version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: petclinic-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CATALINA_OPTS=-Xmx512m -Xms512m
    networks:
      - petclinic-network

  frontend:
    build: 
      context: ./frontend
    container_name: petclinic-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - petclinic-network

networks:
  petclinic-network:
    driver: bridge